return {
    { 'Shatur/neovim-session-manager', config = G_getConfig('session') },
    { 'windwp/nvim-autopairs', config = G_getConfig('autopairs') },
    { 'windwp/nvim-ts-autotag' },
    { 'blackCauldron7/surround.nvim', config = G_getSetup('surround', { mappings_style = 'surround' }) },
    { 'abecodes/tabout.nvim', config = G_getSetup('tabout', {}) },
    { 'andymass/vim-matchup', event = 'VimEnter' },
    { 'kevinhwang91/nvim-hlslens', config = G_getSetup('hlslens', { calm_down = true, nearest_only = true }) },
    { 'numToStr/Comment.nvim', config = G_getConfig('comment') },
    { 'JoosepAlviste/nvim-ts-context-commentstring' },
    { 'phaazon/hop.nvim', config = G_getSetup('hop', {}) },
    { 'https://gitlab.com/yorickpeterse/nvim-window.git' },
    { 'lewis6991/spaceless.nvim', config = G_getSetup('spaceless', {}) },
    { 'kwkarlwang/bufresize.nvim' },
    {
        'L2AsHdz/smart-splits.nvim',
        branch = 'addHooks',
        config = G_getSetup('smart-splits', {
            resize_mode = {
                hooks = {
                    on_leave = require('bufresize').register,
                },
            },
        }),
    },
    { 'sindrets/winshift.nvim' },
    { 'famiu/bufdelete.nvim' },
    { 'Pocco81/AutoSave.nvim', config = G_getConfig('autosave') },
    { 'ethanholz/nvim-lastplace', config = G_getSetup('nvim-lastplace', {}) },
    { 'gbprod/cutlass.nvim', config = G_getSetup('cutlass', { cut_key = 't', exclude = { 'ns', 'nS' } }) },
    { 'gbprod/substitute.nvim', config = G_getSetup('substitute', {}) },
    -- { 'gbprod/yanky.nvim', config = getSetup('yanky', {}) },
    { 'dstein64/vim-startuptime', cmd = 'StartupTime' },
    { 'mg979/vim-visual-multi', branch = 'master' },
    -- { 'numToStr/Navigator.nvim', config = getSetup('Navigator', {}) },
    { 'ghillb/cybu.nvim', config = G_getConfig('cybu') },
    { 'max397574/better-escape.nvim', config = G_getSetup('better_escape', { mapping = { 'ii' } }) },
    { 'AckslD/nvim-neoclip.lua', config = G_getSetup('neoclip', {}) },
    { 'nathom/filetype.nvim' },
}
